### ISSUE TITLE
OpenShift 4 instance issue

### ISSUE THREAD

**Issue by T0hha** [iteratec/multi-juicer#117]
Hi team,

I've installed multi-juicer on OpenShift 4 corporate instance from DockerHub and everything looks fine except it doesn't create new teams. When I check pod's log I see there following message:

time="2022-05-25T14:59:03.974Z" level="info" msg="JuiceBalancer listening on port 3000!"
time="2022-05-25T14:59:22.404Z" level="error" msg="Encountered unknown error while checking for existing JuiceShop deployment"
time="2022-05-25T14:59:22.404Z" level="error" msg="deployments.apps "t-team1-juiceshop" is forbidden: User "system:serviceaccount:cp-429991:default" cannot get resource "deployments" in API group "apps" in the namespace "default""

Is there any workaround to fix it? I can create and bind roles only within the namespace of the project.

**Comment by J12934** [comment]
Hey @T0hha 👋

Can you give me some more details on how you've installed MultiJuicer? (Just `helm install multi-juicer multi-juicer/multi-juicer`?)

MultiJuicer is always "just" scoped to a single namespace so it should work for your setup. During the helm install the used namespace get's set in the config map (`kubectl get configmap -oyaml juice-balancer-config`) In the config.json of the config map there should be a namespace field which is set to your namespace (`cp-429991`).

If you have installed MultiJuicer not using `helm install` but using `helm template` and then later apply this using `oc apply` / `kubectl apply` then the namespace will be incorrectly set. If you explicitly set the namespace (`helm template --namespace cp-429991 ...` the namespace should be properly set in the config.

**Comment by T0hha** [comment]
Thank you for such a quick reply. I installed it without helm but directly from docker image. Is it completely a wrong way and I should install it only with helm?

**Comment by J12934** [comment]
Yes, when you only install the one container it'll miss most of it's configuration.

Installing via helm ensures that all everything is there as expected, I'm actually surprised that MultiJuicer got that far without without it 😅

**Comment by T0hha** [comment]
OK, with helm it works ;) Thanks
