### ISSUE TITLE
After click on "Start Hacking" only forwarded to the start page (with new team-name)

### ISSUE THREAD

**Issue by ChristopherLenz** [iteratec/multi-juicer#119]
Hello, 

I installed the latest version on a Kubernetes cluster. External accessibility with the help of the load balancer is not a problem at all.

As soon as I enter a team name, I get to the page with the access code and a message that the shop is starting up. This takes about 10-15 seconds and the button (Start Hacking) appears for the supposed juice shop. As soon as I click on it, I come back to the start page, where I can select a team name again.

If I use the same team name again, it correctly asks for the access code. But even here I only land on the start page.

If I use the "Admin" team, I get to the admin overview. Here I am told that there are no teams yet.

In Kubernetes, I see the team's matching pod.

What could be the reason?

**Comment by J12934** [comment]
Hi @ChristopherLenz 👋

Can you check if your browser sets the cookie `balancer` when you join the team?

Might be related to the browser blocking the cookie.
Might be because of browser plugins, or if the cookie is configured as https only and the page is served under htt, then the browser would refuse to set it.

**Comment by ChristopherLenz** [comment]
> Can you check if your browser sets the cookie `balancer` when you join the team?

I already checked this and there was no cookie set.

> Might be related to the browser blocking the cookie.
> Might be because of browser plugins, or if the cookie is configured as https only and the page is served under htt, then the > browser would refuse to set it.

Good tip. I'll check. 
Yesterday I had the suspicion that my too complex "cookieParserSecret" could pose a problem. But by then I had already demolished the area and had no more time.

As soon as I have an update I will report back

**Comment by ChristopherLenz** [comment]
my fault...
It was the combination of HTTP and `balancer.cookie.secure = true`
