### ISSUE TITLE
Issues when trying to customize shop with values.yml

### ISSUE THREAD

**Issue by m4riio21** [iteratec/multi-juicer#156]
Hi there,

I'm trying to build a custom shop look for an internal CTF using juice shop, i've been able to modify the shop title and logo modifying it in values.yml but when I try to add the "products" section on it, the juice shop instance will not load.

I'm using multi-juicer with kubernetes with the following setup:

`minikube start`
`helm install multi-juicer multi-juicer/multi-juicer -f multi-juicer/helm/multi-juicer/test.yml`

I've also tried using one of the custom yaml provided in the juice shop guide (https://pwning.owasp-juice.shop/part1/customization.html), (tried the Mozilla one) but it will just load the default juice shop looks.

Any help would be appreciated.

**Comment by J12934** [comment]
Hi @m4riio21!
 Sorry didn't see the question before.

You cannot pass the JuiceShop config directly as the values, you need to put it under `juiceShop.config`, see the default values: https://github.com/iteratec/multi-juicer/blob/main/helm/multi-juicer/values.yaml#L90

The values are used to configure everything in MultiJuicer not just the JuiceShop config so its just a subsection in the MultiJuicer config.

Feel free to reopen if there is still something unclear 🙌
