### ISSUE TITLE
New instances are failing with "multi-user-redis"

### ISSUE THREAD

**Issue by blazerguns** [iteratec/multi-juicer#32]
This used to work fine but now I am seeing this issue. Any ideas?

```
Events:
  Type     Reason     Age                From                   Message
  ----     ------     ----               ----                   -------
  Normal   Scheduled  36s                default-scheduler      Successfully assigned default/t-val-juiceshop-79b6488494-bftsr to s0025abl5905
  Normal   Pulled     35s                kubelet, s0025abl5905  Container image "bkimminich/juice-shop:latest" already present on machine
  Normal   Created    35s                kubelet, s0025abl5905  Created container juice-shop
  Normal   Started    34s                kubelet, s0025abl5905  Started container juice-shop
  Normal   Pulling    15s (x3 over 34s)  kubelet, s0025abl5905  Pulling image "iteratec/juice-progress-watchdog"
  Normal   Pulled     12s (x3 over 31s)  kubelet, s0025abl5905  Successfully pulled image "iteratec/juice-progress-watchdog"
  Warning  Failed     12s (x3 over 31s)  kubelet, s0025abl5905  Error: secret "multi-juicer-redis" not found
  Warning  Unhealthy  9s (x11 over 29s)  kubelet, s0025abl5905  Readiness probe failed: Get http://10.244.1.121:3000/rest/admin/application-version: dial tcp 10.244.1.121:3000: connect: connection refused
```
```
[chandv3_adm@sdcnjc ~]$ curl http://10.244.1.121:3000/rest/admin/application-version
{"version":"9.3.1"}
```

**Comment by J12934** [comment]
Hi 👋
I saw Björn already gave you some advise in slack.
If the "migration guide" / a clean install doesn't help, ping us again.
Would be helpful if you could include how you installed the stack and with which version.

**Comment by blazerguns** [comment]
Yes I uninstalled and reinstalled it and it seem to work. My environment is completely offline so I need to get all docker images needed and installer and force not to download images from internet. However I noticed that juice-progress-watchdog image tries to get downloaded even though that image is present offline.

I was not sure what was going on so decided to first get it working on my laptop before trying it in my environment.

I installed minikube with quite generous config
```
#29 minikube config view
- vm-driver: vmware
- cpus: 3
- disk-size: 60g
- log_dir: /usr/local/var/minikubelogs
- memory: 8192
```
With this config I expect multi-juicer should be able to atleast spin up 4 to 5 instances of juice shop.
1. First one worked fine
```
kubectl get pods
NAME                                READY   STATUS      RESTARTS   AGE
cleanup-job-1578952800-jxfsl        0/1     Completed   0          6h54m
cleanup-job-1578956400-cr482        0/1     Completed   0          5h54m
cleanup-job-1578960000-59ft7        0/1     Completed   0          3h57m
cleanup-job-1578963600-gzflv        0/1     Completed   0          3h54m
cleanup-job-1578970800-sbq98        0/1     Completed   0          87m
cleanup-job-1578974400-dvqzw        0/1     Completed   0          50m
juice-balancer-57774b5b8f-zxgbb     1/1     Running     1          6h57m
multi-juicer-redis-master-0         1/1     Running     1          6h57m
multi-juicer-redis-slave-0          1/1     Running     1          6h57m
t-temp-juiceshop-5dc9fccc7d-2x684   2/2     Running     2          5h29m
```
I tried to create another instance of juiceshop but it fails. I dont see any errors in juicybalancer all I get from trying to create is

<img width="999" alt="Screen Shot 2020-01-14 at 3 56 31 pm" src="https://user-images.githubusercontent.com/11381459/72315322-7d40d400-36e6-11ea-8a72-7f80378dc2ad.png">

Max number of instance in values.yaml is 10. Why is this not working?

**Comment by blazerguns** [comment]
minikube version is 1.6.2 uses vmfusion driver and install docker inside vm.

**Comment by J12934** [comment]
Does it not create any deployment in kubernetes at all?
If so please take a look at the logs from the juice-balancer.

**Comment by J12934** [comment]
For the Non Internet environment, you can change the image pull policy using the Helm values from `Always` to `IfNotPresent` or `Never`:
https://github.com/iteratec/multi-juicer/blob/c03f5e8a5aeee06e88e558dad9760668180ca56e/helm/multi-juicer/values.yaml#L1

**Comment by blazerguns** [comment]
The logs read

```
time="2020-01-14T04:41:34.263Z" level="error" msg="READONLY You can't write against a read only replica."
time="2020-01-14T04:43:29.806Z" level="info" msg="Checking if team recom already has a JuiceShop Deployment"
time="2020-01-14T04:43:29.811Z" level="info" msg="Team recom doesn't have a JuiceShop deployment yet"
time="2020-01-14T04:43:29.815Z" level="info" msg="Reached 1/10 instances"
time="2020-01-14T04:43:30.632Z" level="error" msg="Error while creating deployment or service for team recom"
time="2020-01-14T04:43:30.632Z" level="error" msg="READONLY You can't write against a read only replica."
time="2020-01-14T04:43:32.042Z" level="info" msg="Checking if team recom already has a JuiceShop Deployment"
time="2020-01-14T04:43:32.046Z" level="info" msg="Team recom doesn't have a JuiceShop deployment yet"
time="2020-01-14T04:43:32.051Z" level="info" msg="Reached 1/10 instances"
time="2020-01-14T04:43:32.872Z" level="error" msg="Error while creating deployment or service for team recom"
time="2020-01-14T04:43:32.872Z" level="error" msg="READONLY You can't write against a read only replica."
time="2020-01-14T04:43:43.479Z" level="info" msg="Checking if team recom already has a JuiceShop Deployment"
time="2020-01-14T04:43:43.484Z" level="info" msg="Team recom doesn't have a JuiceShop deployment yet"
time="2020-01-14T04:43:43.488Z" level="info" msg="Reached 1/10 instances"
time="2020-01-14T04:43:44.254Z" level="error" msg="Error while creating deployment or service for team recom"
time="2020-01-14T04:43:44.254Z" level="error" msg="READONLY You can't write against a read only replica."
```

What does that mean?

**Comment by blazerguns** [comment]
> For the Non Internet environment, you can change the image pull policy using the Helm values from `Always` to `IfNotPresent` or `Never`:
> 
> https://github.com/iteratec/multi-juicer/blob/c03f5e8a5aeee06e88e558dad9760668180ca56e/helm/multi-juicer/values.yaml#L1

Yes I did that already. On this specific offline issue, I will debug a little more

**Comment by J12934** [comment]
`READONLY You can't write against a read only replica. ` Hmmm

It seems to try to persist the state against the Redis read only replica. It should normally write against the primary.

Did you change anything in the Redis confit. Not sure how this could happen 🤷‍♂️

**Comment by J12934** [comment]
Oh I just saw that the imagePullPolicy is missing for the progressWatchdog sidecar of the JuiceShop container. Will fix that later today and release a small fix update.

**Comment by blazerguns** [comment]
Perfect!... thanks a lot. I will check it out once you let me know the fix is in.

**Comment by blazerguns** [comment]
> `READONLY You can't write against a read only replica. ` Hmmm
> 
> It seems to try to persist the state against the Redis read only replica. It should normally write against the primary.
> 
> Did you change anything in the Redis confit. Not sure how this could happen 🤷‍♂️

Nothing, I am using it as it is.

**Comment by J12934** [comment]
I've pushed out a release `2.0.1` where the Image Pull Policy should be applied correctly.
I've also updated the version of the redis helm chart. 

This might or might not help with the redis troubles, still not sure whats that about never seen that error happen before 🤷‍♂️

**Comment by blazerguns** [comment]
You wont believe it, I uninstalled and reinstalled with latest release knowing that the fix wont solve redis problem, but it did. I seem to have gone away. I was able to create atleast 5 instances and seem to be working. I even brought restarted minikube cluster and everything seem to work. The only thing that needs to be tested is imagePullPolicy for progress-watchdog. I will test this out today.

**Comment by J12934** [comment]
I'll close this issue as this seems to be resolved.
