### ISSUE TITLE
Why are successfulJobsHistoryLimit and failedJobsHistoryLimit set to 10?

### ISSUE THREAD

**Issue by dmspils** [iteratec/multi-juicer#35]
Both _successfulJobsHistoryLimit_ and _failedJobsHistoryLimit_ are set by default to 10 which seems to consume resources in K8s (100mCPU per process). Is there a reason for setting them to 10 and having the process persist after it has completed or is this something I can reduce to a much lower value without any knock on effects or is 10 specified for a reason?

**Comment by J12934** [comment]
This is mostly to have a bit of history to debug if everything is working correctly.

You should be able to decrease it safely. Probably even to zero.

But are you sure about the completed Jobs still consuming resources? Pretty that’s not true.

**Comment by J12934** [comment]
Checked our Instance which is running on OpenShift and it doesn't show any resources used for the completed jobs.
If you want to decrease it anyway we could add a Option to configure this via helm.

**Comment by dmspils** [comment]
Here's an example of one running on GCP:

![image](https://user-images.githubusercontent.com/32258443/73549003-a62ccd00-4439-11ea-97e4-8bfa135e2088.png)

The only reason that I spotted it was that I sized the cluster to the minimum needed for multijuicer just to keep the lights on but with a huge autoscale policy and after a day of running, it tipped over the limit and needed additional nodes which cost $$. Setting the values to 1 means that I stay under the limit and my default node size is minimised again.

Maybe it's a nuance of GCP then?

**Comment by J12934** [comment]
Ah, ok the resources are probably not actually used but just reserved on the nodes.
Will lower the default down to one in the next release.

Thanks for reporting the issue 👍
