### ISSUE TITLE
DigitalOcean configuration naming error

### ISSUE THREAD

**Issue by DiedB** [iteratec/multi-juicer#54]
https://github.com/iteratec/multi-juicer/blob/47cab1dd22e10ffc87492538694973294d1ec6c1/guides/digital-ocean/do-lb.yaml#L17

This selector is not working, resulting in the load balancer not selecting any `juice-balancer` pods. The line should be changed in `app.kubernetes.io/name: multi-juicer`.

**Comment by J12934** [comment]
Oh good catch 👍
Will change this in the docs
