### ISSUE TITLE
Issue deploying mulit-juicer

### ISSUE THREAD

**Issue by skandix** [iteratec/multi-juicer#57]
Helm Version: 
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

I'm trying to deploy multi-juicer with the use of this command 
```bash
helm install -f values.yaml multi-juicer ./multi-juicer/helm/multi-juicer
```

But I get the error, ``Error: This command needs 1 argument: chart name``

**Comment by J12934** [comment]
Hi 👋 
This seems to be a argument / hem version mismatch as the argument structure between helm v3 and Helm v2 is a bit different.

If you have the option to upgrade to use helm v3, I'd recommend to use v3, it's just a lot easier to use. On v3 the command you've posted should work.

If you want / need to stick to helm v2 the command needs to have only one argument and the name of the release needs to be specified via a flag, this should look something like this. (From memory, haven't used helm v2 in a while 😀)

```
helm install -f values.yaml --name multi-juicer ./multi-juicer/helm/multi-juicer
```

**Comment by skandix** [comment]
aha, I think i'll just go through with upgrading to Helm3 thanks anyways :)

**Comment by J12934** [comment]
I'm guessing this is resolved now ;)
Will close this, to for an better overview.

If you run into more problems, feel free to reopen this or open another ticket.
