### ISSUE TITLE
Template variables could not be initialized: Datasource named Prometheus was not found

### ISSUE THREAD

**Issue by canyakan99** [iteratec/multi-juicer#65]
Hi,

i have a problem with setting up the Multi-Juicer with a monitoring setup. I have followed the guides for the monitoring setup and installed everything. 
I installed Grafana with the commands (https://github.com/grafana/helm-charts/tree/main/charts/grafana) and set the attribut _sidecar.datasource.enabled_ to _true_ in the _values.yaml_ file from Grafana. 
Then I called Grafana in the browser to view the dashboard. The problem is that firstly the error message "Template variables could not be initialized: Datasource named Prometheus was not found" appears and secondly the data in the dashboard is completely random and does not reflect statistics of any Juice Shop instance. 
Do you know how to solve this problem? Basically, I just followed the guides and ended up with the error message.

**Comment by J12934** [comment]
Hi @canyakan99 👋

How much did you follow the [monitoring setup guide]()?

The monitoring setup guide recommends to install the [prometheus-community/kube-prometheus-stack](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack) not the grafana chart you've linked to. The one you linked to only is a standalone Grafana instance, which also explains why it can't find the Prometheus datasource.

**Comment by J12934** [comment]
Inactive, closing.
