### ISSUE TITLE
connectionCache

### ISSUE THREAD

**Issue by troygerber** [iteratec/multi-juicer#68]
The checkIfInstanceIsUp function in proxy.js uses req.cleanedTeamname to check for the team in the cache. The updateLastConnectTimestamp function uses req.teamname to add the team to the cache. I added some logging and noticed that the checkIfInstanceIsUp function never finds the team in the cache and always calls getJuiceShopInstanceForTeamname(teamname) which adds quite a bit of time to every request. updateLastConnectTimestamp seems to add t-teamname and checkIfInstanceIsUp checks just for teamname. Both functions should use the same version of the teamname for the cache.

**Comment by J12934** [comment]
Oh, this sounds like a really good catch 👍

Do you mind creating a PR with the fix? Would love to take a look at it

**Comment by J12934** [comment]
Closed via #72
