### ISSUE TITLE
Public access deployed on Azure

### ISSUE THREAD

**Issue by y2kkarthik** [iteratec/multi-juicer#79]
I am new here and I followed the steps to deploy multi-juicer on AKS and tried port forwarding to access from my local machine. Unfortunately it doesn't work. Do I need to change anything on the Azure side to have public access? 

Appreciate your help and thank you in advance 

Regards,
Karthik

**Comment by J12934** [comment]
Hi 👋
`kubectl port-forward` should work 🤔.
One of the things which might interfere with that would be if you set up the cluster to be in a restrictive VPC.

@JamesMatchett recently opened up pr #77 which expands the Azure guide and added instructions to expose MultiJuicer via Ingress on Azure, you can try that out.
